name: 'Setup and install'
description: 'Common setup steps for Actions'
inputs:
  node-version:
    description: 'Version of Node.js'
    required: true
    default: 20

runs:
  using: composite
  steps:
    - shell: bash
      run: npm i -g pnpm@^9 turbo

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - uses: actions/checkout@v4

    - shell: bash
      run: pnpm install
