name: 'Setup and install'
description: 'Common setup steps for Actions'

runs:
  using: composite
  steps:
    - shell: bash
      run: npm i -g pnpm@^9 turbo

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - uses: actions/checkout@v4

    - shell: bash
      run: pnpm install
